### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Ak-na** [sviatoslav-lebediev/anki-quizlet-importer-extended#90] opened 2023-06-07 15:36 UTC
Getting the same error on several quizlets, went through a set of 28 decks, 15 of which wouldn't import, tried using page html too.

https://quizlet.com/711838030/comptia-a-1101-network-tools-flash-cards/?funnelUUID=1a36782b-9376-4914-917a-8bfbff41a6b9
https://quizlet.com/711841330/comptia-a-1101-memory-flash-cards/?funnelUUID=f1ae96a4-276f-49bb-a085-428b2f3db897
https://quizlet.com/711842243/comptia-a-1101-motherboard-expansion-slots-flash-cards/?funnelUUID=2af4c857-4aa4-4204-a5ea-231fa038b609
https://quizlet.com/711844113/comptia-a-1101-cloud-flash-cards/?funnelUUID=50ee2698-d972-4039-b1a4-740bd77c3dfe
https://quizlet.com/711844792/comptia-a-1101-troubleshooting-flash-cards/?funnelUUID=738878e8-c5ca-4030-adbb-3fdef2798e42
https://quizlet.com/711835055/comptia-a-1101-networking-services-2-flash-cards/?funnelUUID=177af794-843e-4ba8-8b19-790925c0343c
https://quizlet.com/711836202/comptia-a-1101-assigning-ip-addresses-dhcp-configuration-flash-cards/?funnelUUID=99b93e95-4b3e-45a5-a587-422b111fcf59
https://quizlet.com/712112760/comptia-a-1101-dns-dns-records-flash-cards/?funnelUUID=3f783aea-7f06-4957-a5ed-68955a626ce1
https://quizlet.com/711838639/comptia-a-1101-network-cables-flash-cards/?funnelUUID=af5dedbf-3a31-4ecc-b680-f564c91b2f42
https://quizlet.com/711839631/comptia-a-1101-video-cables-flash-cards/?funnelUUID=84b5ff56-fb37-48c1-b307-50bd779a4fc7
https://quizlet.com/711841923/comptia-a-1101-raid-flash-cards/?funnelUUID=4ce77d45-6367-4ff0-b372-330eb63fdf89
https://quizlet.com/711844526/comptia-a-1101-virtualization-flash-cards/?funnelUUID=b66262e2-8166-4ad4-bf11-56e356d319c5
https://quizlet.com/711833503/comptia-a-1101-wireless-network-standards-channels-flash-cards/?funnelUUID=5ef4b8e3-d9ba-489b-ac38-52b87d38adb7
https://quizlet.com/711832154/comptia-a-1101-network-devices-flash-cards/?funnelUUID=e5eae7b0-77b1-46c1-943a-db8a85f375d9
https://quizlet.com/711831375/comptia-a-1101-networking-services-and-protocols-1-flash-cards/?funnelUUID=fc2c58c9-32c0-41e0-81b5-098203cc0f04

[1a36782b-9376-4914-917a-8bfbff41a6b9.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679375/1a36782b-9376-4914-917a-8bfbff41a6b9.txt)
[f1ae96a4-276f-49bb-a085-428b2f3db897.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679376/f1ae96a4-276f-49bb-a085-428b2f3db897.txt)
[2af4c857-4aa4-4204-a5ea-231fa038b609.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679377/2af4c857-4aa4-4204-a5ea-231fa038b609.txt)
[50ee2698-d972-4039-b1a4-740bd77c3dfe.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679378/50ee2698-d972-4039-b1a4-740bd77c3dfe.txt)
[738878e8-c5ca-4030-adbb-3fdef2798e42.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679379/738878e8-c5ca-4030-adbb-3fdef2798e42.txt)
[177af794-843e-4ba8-8b19-790925c0343c.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679380/177af794-843e-4ba8-8b19-790925c0343c.txt)
[99b93e95-4b3e-45a5-a587-422b111fcf59.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679381/99b93e95-4b3e-45a5-a587-422b111fcf59.txt)
[3f783aea-7f06-4957-a5ed-68955a626ce1.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679382/3f783aea-7f06-4957-a5ed-68955a626ce1.txt)
[af5dedbf-3a31-4ecc-b680-f564c91b2f42.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679383/af5dedbf-3a31-4ecc-b680-f564c91b2f42.txt)
[84b5ff56-fb37-48c1-b307-50bd779a4fc7.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679384/84b5ff56-fb37-48c1-b307-50bd779a4fc7.txt)
[4ce77d45-6367-4ff0-b372-330eb63fdf89.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679385/4ce77d45-6367-4ff0-b372-330eb63fdf89.txt)
[b66262e2-8166-4ad4-bf11-56e356d319c5.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679386/b66262e2-8166-4ad4-bf11-56e356d319c5.txt)
[5ef4b8e3-d9ba-489b-ac38-52b87d38adb7.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679387/5ef4b8e3-d9ba-489b-ac38-52b87d38adb7.txt)
[e5eae7b0-77b1-46c1-943a-db8a85f375d9.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679388/e5eae7b0-77b1-46c1-943a-db8a85f375d9.txt)
[fc2c58c9-32c0-41e0-81b5-098203cc0f04.txt](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11679389/fc2c58c9-32c0-41e0-81b5-098203cc0f04.txt)

**Comment by sviatoslav-lebediev** [comment] 2023-06-07 21:11
@Ak-na and you receive these errors even when you use the HTML mode, did I understand you correctly ?
because I've tried 1 deck and I can import it.
If you don't need audio - try to uncheck `Download audio`. It can help as well for some cases.
[CompTIA A+ 1101 Networking Services and Protocols 1.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11681971/CompTIA.A%2B.1101.Networking.Services.and.Protocols.1.apkg.zip)

**Comment by giulia1235** [comment] 2023-06-12 07:46
i'm having the same problem too, over and over again. I've tried to uncheck "download audio" and also check "skip errors" but nothing changed. 

the deck i want to import is this: https://quizlet.com/809388470/flashcards

**Comment by giulia1235** [comment] 2023-06-12 07:53
> i'm having the same problem too, over and over again. I've tried to uncheck "download audio" and also check "skip errors" but nothing changed.
> 
> the deck i want to import is this: https://quizlet.com/809388470/flashcards

the problem is always with the "add reverse" bottom. If i just check the "skip errors" box, it will work. But i need to import also the reverse cards and that seems not to work in any way.

**Comment by DrNCognito** [comment] 2023-06-13 04:40
Also having the same problem, regardless of options boxes checked or unchecked, using URL or the source HTML code.  An example card set:  https://quizlet.com/be/669779487/unidad-0-introduccion-pedro-flash-cards/

**Comment by sviatoslav-lebediev** [comment] 2023-06-13 09:14
@DrNCognito this deck is private, could you try to make it public, import, make it private again ?

**Comment by sviatoslav-lebediev** [comment] 2023-06-13 09:31
@giulia1235 I've tried to import your deck and haven't had any issues. If you have a problem when you check `Add reverse` it 99% means that you somehow have changed a `Basic Quizlet Extended` note type and the add-on can set required fields. Try to click on Tools/Manage Note Types and remove `Basic Quizlet Extended`, the add-on will recreate it.

p.s This add-on adds reversed cards when you check that checkbox but you can do it manually https://docs.ankiweb.net/templates/generation.html#reverse-cards

your deck [U-6.apkg.zip](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/files/11733198/U-6.apkg.zip)

**Comment by MOGUL1224** [comment] 2023-06-16 01:36
@sviatoslav-lebediev The error is back. I am getting: "Expecting value: line 1 column 1" error no matter what I do. I've tried everything.

**Comment by sviatoslav-lebediev** [comment] 2023-06-16 10:13
@MOGUL1224 yep, it looks like quizlet has changed something again :) I need time to fix the add-on. Will ping you when it's done

**Comment by MOGUL1224** [comment] 2023-06-16 12:07
@sviatoslav-lebediev I hope you'll be able to fix it as soon as possible. The exam is coming XD.

**Comment by sviatoslav-lebediev** [comment] 2023-06-19 09:24
I'm going to close this issue, create a new one if you still can't import

**Closed by sviatoslav-lebediev** 2023-06-19 09:24 UTC
