### ISSUE TITLE
'cardSides' error

### ISSUE THREAD

**Issue by graceebrookss** [sviatoslav-lebediev/anki-quizlet-importer-extended#74] opened 2023-05-13 20:05 UTC
I just downloaded the add-on and it worked perfectly for the first deck that I imported. I tried to import the next and received the error below. I tried to import a different deck and received the same error.

Error:
 'cardSides'
-----------------
{"responses":[{"models":{"studiableItem":[{"id":7732506326,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1508174687},{"id":9807875749,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1525290734},{"id":9807910584,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1525290967},{"id":9807963687,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1536271697},{"id":7732506327,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1588266354},{"id":10012957037,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526852892},{"id":10013120456,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526946484},{"id":10013127783,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854005},{"id":9808216955,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1564008837},{"id":10013160983,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854214},{"id":10013204848,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854563},{"id":7732506328,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526941050},{"id":9808117993,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":10013000531,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506329,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1597168039},{"id":7732506330,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506331,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506332,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":9808275969,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":9808294751,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1600046911},{"id":9808342664,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1536273748},{"id":9808376616,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1536273896},{"id":7732506333,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":10013084474,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":10013095308,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506334,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":9808430496,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":9808451089,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":9808491522,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506336,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1536274750},{"id":7732506335,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1536274750},{"id":7732506337,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506338,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506339,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506340,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506341,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506342,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506343,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506344,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":9808825415,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506345,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1587148514},{"id":7732506346,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506347,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506348,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506349,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506350,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1589147410},{"id":7732506351,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506352,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506353,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506354,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506355,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506356,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506357,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506358,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506359,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506360,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506361,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506362,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506363,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484},{"id":7732506364,"studiableContainerType":1,"studiableContainerId":234422715,"isDeleted":true,"lastModified":1526854484}]},"paging":{"total":60,"page":1,"perPage":1000,"token":"qVjzchZHmP.b8UMccHTXEmQ4gfgT"}}]}

Quizlet deck URL: https://quizlet.com/234422511/biology-i-module-of-the-mcat-self-prep-ecourse-lesson-2-brain-structure-pro-flash-cards/?funnelUUID=d295644e-fd34-40f6-bdd2-0181edcd2dc9

also tried with: https://quizlet.com/234422715/biology-i-module-of-the-mcat-self-prep-ecourse-lesson-3-studying-the-brain-pro-flash-cards/?funnelUUID=69ac797d-82b4-42ab-842a-52b1208c72eb

**Comment by sviatoslav-lebediev** [comment] 2023-05-14 13:23
Hi, I guess the problem is that these decks are private. If they are yours I would try making them public, import, and then make them private again.

**Comment by sviatoslav-lebediev** [comment] 2023-05-14 13:24
another option - try to set cookies
To download your own private or password-protected sets, go to Tools - Add-ons - Improved Quizlet ... - Config and either set "cookies" or "qlts" and click OK.
To set "cookies", open Chrome DevTools, click the Network tab, reload the page or press Ctrl+R, click on the first request and copy "cookies" value from the request headers.
To set "qlts", open Chrome DevTools, click the Application tab, and copy "qlts" value from the Cookies pane - https://developers.google.com/web/tools/chrome-devtools/storage/cookies.
If "qlts" is set, it takes precedence over "cookies". Once it's done it should be possible to download private or password-protected sets for a limited period of time without making them public.

**Comment by sviatoslav-lebediev** [comment] 2023-05-27 19:04
I will close this ticket, re-open it, or create a new one if you still can't import decks.

**Closed by sviatoslav-lebediev** 2023-05-27 19:04 UTC
